idf_component_register(SRCS "main.c"
                            "can.c"
                            "cmd_can.c"
                            "cmd_system.c"
                            "cmd_utils.c"
                            "console.c"
                            "fs.c"
                            "xvprintf.c"
                       INCLUDE_DIRS ".")
